// la palabra mock se utiliza en programacion para indicar los archivos que simulan algo... otro ejemplo = userMock

export const products = [
    {
        id: 1,
        title: "NIKE AF1 LOW LUOIS VITTUON CUSTOM BLACK",
        description: "Discover the Nike AF1 Low Louis Vuitton. A fusion of luxury and urban style to stand out with every step. Get your hands on them and make a difference!",
        price: 470,
        stock: 8,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270303/eCommerce/products/NIKE_AF1_LOW_LUOIS_VITTUON_CUSTOM_BLACK_gn6w0r.png",
        category: "men",
    },
    {
        id: 2,
        title: "NIKE VAPORMAX 2.0 RUST PINK",
        description: "Discover the Nike VaporMax 2.0 Rust Pink. Style and comfort with every step. Get them now!",
        price: 430,
        stock: 5,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270303/eCommerce/products/NIKE_VAPORMAX_2.0_RUST_PINK_qkeicn.png",
        category: "women",
    },
    {
        id: 3,
        title: "NIKE AJ1 RETRO HIGH OBSIDIAN UNC",
        description: "Discover the Nike AJ1 Retro High Obsidian UNC. Style and legacy with every step. Essential in your collection!",
        price: 510,
        stock: 9,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270304/eCommerce/products/NIKE_AJ1_RETRO_HIGH_OBSIDIAN_UNC_ke5kq0.png",
        category: "men",
    },
    {
        id: 4,
        title: "NIKE AF1 LOW VALENTINES'S DAY 2022",
        description: "Discover the Nike AF1 Low Valentine's Day 2022. Romantic style to shine with every step. Essential in your collection!",
        price: 490,
        stock: 8,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270303/eCommerce/products/NIKE_AF1_LOW_VALENTINES_S_DAY_2022_gz53nu.png",
        category: "women",
    },
    {
        id: 5,
        title: "NIKE MORE UPTEMPO BROWN BULLS",
        description: "Discover the Nike More Uptempo Brown Bulls. Bold and sporty style with every step. Essential for basketball fans!",
        price: 520,
        stock: 6,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270304/eCommerce/products/NIKE_MORE_UPTEMPO_BROWN_BULLS_u1qpji.png",
        category: "men",
    },
    {
        id: 6,
        title: "NIKE AIR MAX TN PLUS CITY SPECIAL ATL",
        description: "Discover the Nike Air Max TN Plus City Special ATL. Urban and authentic style with every step. Essential for Atlanta lovers!",
        price: 380,
        stock: 7,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270303/eCommerce/products/NIKE_AIR_MAX_TN_PLUS_CITY_SPECIAL_ATL_fdkzse.png",
        category: "women",
    },
    {
        id: 7,
        title: "AJ1 MID DIGITAL PINK",
        description: "Discover the AJ1 Mid Digital Pink. Bold and vibrant style with every step. Essential in your collection!",
        price: 510,
        stock: 7,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270302/eCommerce/products/AJ1_MID_DIGITAL_PINK_qj4pss.png",
        category: "women",
    },
    {
        id: 8,
        title: "ADIDAS YEEZY BOOST 350 V2 NATURAL",
        description: "Discover the Adidas Yeezy Boost 350 V2 Natural. Minimalistic style and unparalleled comfort. Essential in your collection!",
        price: 340,
        stock: 9,
        img: "https://res.cloudinary.com/dy3natzfk/image/upload/v1688270282/eCommerce/products/ADIDAS_YEEZY_BOOST_350_V2_NATURAL_xngata.png",
        category: "men",
    },
]